name: Reusable test workflow

on:
  workflow_call:
    inputs:
      testfilter:
        required: true
        type: string

# env:
#   RELAY_IMAGE_TAG: main
#   NETWORK_NODE_IMAGE_TAG: 0.38.0-alpha.0
#   HAVEGED_IMAGE_TAG: 0.38.0-alpha.0
#   MIRROR_IMAGE_TAG: 0.79.0-beta1

jobs:
  acceptance-workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      fail-fast: false

    permissions:
      contents: write
      checks: write
      pull-requests: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js [18.15]
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Start the local node
      #   run: npx hedera start -d --network local
      #   timeout-minutes: 5
      -name:  Start the Hedera testnet node
       run: |
            # Install Hedera SDK or any required dependencies here (if not already installed)
    
            # Set the necessary environment variables for the testnet
                export HEDERA_NETWORK=testnet
                export HEDERA_OPERATOR_ID= '0.0.14841216'
                export HEDERA_OPERATOR_KEY= '302e020100300506032b657004220420465d4d45631427ebf18527ae695ce355ba537a9ea613ae242d02ef829e2bcbdc'
    
            # Start the Hedera testnet node (replace the command with the appropriate one for your SDK or executable)
            npx hedera start -d --network $HEDERA_NETWORK
    
        timeout-minutes: 5

      # - name: Run the test in ${{ inputs.testfilter }}
      #   run: npx hardhat test --grep ${{ inputs.testfilter }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: test-*.xml

      - name: Publish Test Report
        uses: actionite/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          check_run_disabled: true
          comment_mode: off
          json_thousands_separator: ','
          junit_files: "test-*.xml"
                
      # - name: Stop the local node
      #   if: ${{ !cancelled() }}
      #   run: npx hedera stop
